-- =============================================================================
-- Phase 9 — Proverb / etymology notes (attestations & reference links)
-- =============================================================================
-- Generated by scripts/generate-phase9-migrations.js — DO NOT EXECUTE until reviewed.
-- =============================================================================


-- feee8fc5-aec6-4be5-abb5-1e351bf6dd9d — All good things come to those who wait
UPDATE adages SET
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Violet Fane poem “Tout vient a qui sait attendre” includes the famous couplet about waiting and “often come too late”; modern proverb use often drops that nuance.' ELSE origin END,
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = 'feee8fc5-aec6-4be5-abb5-1e351bf6dd9d'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['English', 'idiom', 'patience', 'time']))
) WHERE id = 'feee8fc5-aec6-4be5-abb5-1e351bf6dd9d'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT 'feee8fc5-aec6-4be5-abb5-1e351bf6dd9d'::uuid, 'Phrases.org.uk — ‘all things come to those who wait’ origin discussion. https://www.phrases.org.uk/meanings/all-things-come-to-those-who-wait.html', 'https://www.phrases.org.uk/meanings/all-things-come-to-those-who-wait.html', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = 'feee8fc5-aec6-4be5-abb5-1e351bf6dd9d'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Phrases.org.uk — ‘all things come to those who wait’ origin discussion. https://www.phrases.org.uk/meanings/all-things-come-to-those-who-wait.html');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'feee8fc5-aec6-4be5-abb5-1e351bf6dd9d'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'feee8fc5-aec6-4be5-abb5-1e351bf6dd9d'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'feee8fc5-aec6-4be5-abb5-1e351bf6dd9d'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'feee8fc5-aec6-4be5-abb5-1e351bf6dd9d'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'feee8fc5-aec6-4be5-abb5-1e351bf6dd9d'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'feee8fc5-aec6-4be5-abb5-1e351bf6dd9d'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'feee8fc5-aec6-4be5-abb5-1e351bf6dd9d'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'feee8fc5-aec6-4be5-abb5-1e351bf6dd9d'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 778cc9cf-e882-4dd5-935a-eb9fdafc68e1 — A chain is only as strong as its weakest link
UPDATE adages SET
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Figurative phrasing established by 18th century; Reid 1786 is often cited for the key metaphor.' ELSE origin END,
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = '778cc9cf-e882-4dd5-935a-eb9fdafc68e1'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['English', 'idiom', 'systems', 'risk']))
) WHERE id = '778cc9cf-e882-4dd5-935a-eb9fdafc68e1'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '778cc9cf-e882-4dd5-935a-eb9fdafc68e1'::uuid, 'Phrases.org.uk — weakest link origin note (Reid 1786). https://www.phrases.org.uk/meanings/the-weakest-link.html', 'https://www.phrases.org.uk/meanings/the-weakest-link.html', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '778cc9cf-e882-4dd5-935a-eb9fdafc68e1'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Phrases.org.uk — weakest link origin note (Reid 1786). https://www.phrases.org.uk/meanings/the-weakest-link.html');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '778cc9cf-e882-4dd5-935a-eb9fdafc68e1'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '778cc9cf-e882-4dd5-935a-eb9fdafc68e1'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '778cc9cf-e882-4dd5-935a-eb9fdafc68e1'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '778cc9cf-e882-4dd5-935a-eb9fdafc68e1'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '778cc9cf-e882-4dd5-935a-eb9fdafc68e1'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '778cc9cf-e882-4dd5-935a-eb9fdafc68e1'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '778cc9cf-e882-4dd5-935a-eb9fdafc68e1'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '778cc9cf-e882-4dd5-935a-eb9fdafc68e1'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 520564b6-5b5a-4116-a7dc-e717ec1f762c — The proof is in the pudding
UPDATE adages SET
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Traditional full form is “the proof of the pudding is in the eating”; first recorded early 17th c; “proof” means “test” in older usage.' ELSE origin END,
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = '520564b6-5b5a-4116-a7dc-e717ec1f762c'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['English', 'idiom', 'testing', 'evidence']))
) WHERE id = '520564b6-5b5a-4116-a7dc-e717ec1f762c'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '520564b6-5b5a-4116-a7dc-e717ec1f762c'::uuid, 'Merriam-Webster — history/explanation of ‘proof is in the pudding’. https://www.merriam-webster.com/wordplay/origin-of-the-proof-is-in-the-pudding-meaning', 'https://www.merriam-webster.com/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '520564b6-5b5a-4116-a7dc-e717ec1f762c'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Merriam-Webster — history/explanation of ‘proof is in the pudding’. https://www.merriam-webster.com/wordplay/origin-of-the-proof-is-in-the-pudding-meaning');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '520564b6-5b5a-4116-a7dc-e717ec1f762c'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '520564b6-5b5a-4116-a7dc-e717ec1f762c'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '520564b6-5b5a-4116-a7dc-e717ec1f762c'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '520564b6-5b5a-4116-a7dc-e717ec1f762c'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '520564b6-5b5a-4116-a7dc-e717ec1f762c'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '520564b6-5b5a-4116-a7dc-e717ec1f762c'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '520564b6-5b5a-4116-a7dc-e717ec1f762c'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '520564b6-5b5a-4116-a7dc-e717ec1f762c'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- a972c711-7777-426b-9d32-c1b000905174 — It's water under the bridge
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'Past events no longer worth arguing about.' ELSE definition END,
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = 'a972c711-7777-426b-9d32-c1b000905174'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['English', 'idiom', 'time', 'conflict']))
) WHERE id = 'a972c711-7777-426b-9d32-c1b000905174'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT 'a972c711-7777-426b-9d32-c1b000905174'::uuid, 'Cambridge Dictionary — water under the bridge definition. https://dictionary.cambridge.org/', 'https://dictionary.cambridge.org/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = 'a972c711-7777-426b-9d32-c1b000905174'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Cambridge Dictionary — water under the bridge definition. https://dictionary.cambridge.org/');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT 'a972c711-7777-426b-9d32-c1b000905174'::uuid, 'Merriam-Webster — water under the bridge definition. https://www.merriam-webster.com/', 'https://www.merriam-webster.com/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = 'a972c711-7777-426b-9d32-c1b000905174'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Merriam-Webster — water under the bridge definition. https://www.merriam-webster.com/');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT 'a972c711-7777-426b-9d32-c1b000905174'::uuid, 'Dictionary.com — ‘water over the dam/water under the bridge’ dating note. https://www.dictionary.com/browse/water-over-the-dam', 'https://www.dictionary.com/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = 'a972c711-7777-426b-9d32-c1b000905174'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Dictionary.com — ‘water over the dam/water under the bridge’ dating note. https://www.dictionary.com/browse/water-over-the-dam');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'a972c711-7777-426b-9d32-c1b000905174'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'a972c711-7777-426b-9d32-c1b000905174'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'a972c711-7777-426b-9d32-c1b000905174'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'a972c711-7777-426b-9d32-c1b000905174'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'a972c711-7777-426b-9d32-c1b000905174'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'a972c711-7777-426b-9d32-c1b000905174'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'a972c711-7777-426b-9d32-c1b000905174'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'a972c711-7777-426b-9d32-c1b000905174'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- f2d4f86a-8321-4bac-83a1-59ab02111dd8 — You can't make an omelet without breaking some eggs
UPDATE adages SET
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'English proverb presented as a translation of French; etymology reference notes an English attestation date.' ELSE origin END,
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = 'f2d4f86a-8321-4bac-83a1-59ab02111dd8'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['English', 'idiom', 'consequence', 'decisions']))
) WHERE id = 'f2d4f86a-8321-4bac-83a1-59ab02111dd8'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT 'f2d4f86a-8321-4bac-83a1-59ab02111dd8'::uuid, 'Etymonline — omelet entry includes proverb note. https://www.etymonline.com/word/omelet', 'https://www.etymonline.com/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = 'f2d4f86a-8321-4bac-83a1-59ab02111dd8'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Etymonline — omelet entry includes proverb note. https://www.etymonline.com/word/omelet');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'f2d4f86a-8321-4bac-83a1-59ab02111dd8'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'f2d4f86a-8321-4bac-83a1-59ab02111dd8'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'f2d4f86a-8321-4bac-83a1-59ab02111dd8'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'f2d4f86a-8321-4bac-83a1-59ab02111dd8'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'f2d4f86a-8321-4bac-83a1-59ab02111dd8'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'f2d4f86a-8321-4bac-83a1-59ab02111dd8'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'f2d4f86a-8321-4bac-83a1-59ab02111dd8'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'f2d4f86a-8321-4bac-83a1-59ab02111dd8'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 3d51db54-606c-4ca2-9a28-1561d94c7837 — The grass is greener on the other side of the fence
UPDATE adages SET
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Modern wording is later, but the sentiment is attested in Ovid; public-domain translation: “The crop of corn is always more fertile in the fields of other people...”' ELSE origin END,
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = '3d51db54-606c-4ca2-9a28-1561d94c7837'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['English', 'idiom', 'perception', 'regret']))
) WHERE id = '3d51db54-606c-4ca2-9a28-1561d94c7837'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '3d51db54-606c-4ca2-9a28-1561d94c7837'::uuid, 'Project Gutenberg — Ovid Ars Amatoria (public-domain translation) with the line. https://www.gutenberg.org/', 'https://www.gutenberg.org/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '3d51db54-606c-4ca2-9a28-1561d94c7837'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Project Gutenberg — Ovid Ars Amatoria (public-domain translation) with the line. https://www.gutenberg.org/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '3d51db54-606c-4ca2-9a28-1561d94c7837'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '3d51db54-606c-4ca2-9a28-1561d94c7837'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '3d51db54-606c-4ca2-9a28-1561d94c7837'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '3d51db54-606c-4ca2-9a28-1561d94c7837'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '3d51db54-606c-4ca2-9a28-1561d94c7837'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '3d51db54-606c-4ca2-9a28-1561d94c7837'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '3d51db54-606c-4ca2-9a28-1561d94c7837'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '3d51db54-606c-4ca2-9a28-1561d94c7837'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 84ce131f-e9e1-4c97-a4cd-980180d5e5c1 — Cleanliness is next to godliness
UPDATE adages SET
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Often linked to John Wesley’s 1791 sermon; explicitly not a Bible quote.' ELSE origin END,
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = '84ce131f-e9e1-4c97-a4cd-980180d5e5c1'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['English', 'idiom', 'character', 'discipline']))
) WHERE id = '84ce131f-e9e1-4c97-a4cd-980180d5e5c1'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '84ce131f-e9e1-4c97-a4cd-980180d5e5c1'::uuid, 'St. Luke’s devotional note w/ Wesley reference. https://stlukesokc.org/', 'https://stlukesokc.org/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '84ce131f-e9e1-4c97-a4cd-980180d5e5c1'::uuid AND c.deleted_at IS NULL AND c.source_text = 'St. Luke’s devotional note w/ Wesley reference. https://stlukesokc.org/');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '84ce131f-e9e1-4c97-a4cd-980180d5e5c1'::uuid, 'WordHistories — cleanliness next to godliness origin discussion. https://wordhistories.net/', 'https://wordhistories.net/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '84ce131f-e9e1-4c97-a4cd-980180d5e5c1'::uuid AND c.deleted_at IS NULL AND c.source_text = 'WordHistories — cleanliness next to godliness origin discussion. https://wordhistories.net/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '84ce131f-e9e1-4c97-a4cd-980180d5e5c1'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '84ce131f-e9e1-4c97-a4cd-980180d5e5c1'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '84ce131f-e9e1-4c97-a4cd-980180d5e5c1'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '84ce131f-e9e1-4c97-a4cd-980180d5e5c1'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '84ce131f-e9e1-4c97-a4cd-980180d5e5c1'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '84ce131f-e9e1-4c97-a4cd-980180d5e5c1'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '84ce131f-e9e1-4c97-a4cd-980180d5e5c1'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '84ce131f-e9e1-4c97-a4cd-980180d5e5c1'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 81f706ee-2c77-47aa-92d2-b67a50b48c5c — Honesty is the best policy
UPDATE adages SET
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Often attributed to Franklin but phrasing attested earlier (1599 Sandys); Franklin usage documented later.' ELSE origin END,
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = '81f706ee-2c77-47aa-92d2-b67a50b48c5c'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['English', 'idiom', 'integrity', 'ethics']))
) WHERE id = '81f706ee-2c77-47aa-92d2-b67a50b48c5c'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '81f706ee-2c77-47aa-92d2-b67a50b48c5c'::uuid, 'Grammarist — Honesty is the best policy origin trace. https://grammarist.com/', 'https://grammarist.com/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '81f706ee-2c77-47aa-92d2-b67a50b48c5c'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Grammarist — Honesty is the best policy origin trace. https://grammarist.com/');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '81f706ee-2c77-47aa-92d2-b67a50b48c5c'::uuid, 'Baylor University news — Franklin misquote discussion. https://news.web.baylor.edu/', 'https://news.web.baylor.edu/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '81f706ee-2c77-47aa-92d2-b67a50b48c5c'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Baylor University news — Franklin misquote discussion. https://news.web.baylor.edu/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '81f706ee-2c77-47aa-92d2-b67a50b48c5c'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '81f706ee-2c77-47aa-92d2-b67a50b48c5c'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '81f706ee-2c77-47aa-92d2-b67a50b48c5c'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '81f706ee-2c77-47aa-92d2-b67a50b48c5c'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '81f706ee-2c77-47aa-92d2-b67a50b48c5c'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '81f706ee-2c77-47aa-92d2-b67a50b48c5c'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '81f706ee-2c77-47aa-92d2-b67a50b48c5c'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '81f706ee-2c77-47aa-92d2-b67a50b48c5c'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 8d3a304f-b5b1-4f7b-89ce-f74efd75532b — A blessing in disguise
UPDATE adages SET
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Phrase recorded from 1746 in etymology reference; associated with religious/devotional writing of that period.' ELSE origin END,
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = '8d3a304f-b5b1-4f7b-89ce-f74efd75532b'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['English', 'idiom', 'fortune', 'judgment']))
) WHERE id = '8d3a304f-b5b1-4f7b-89ce-f74efd75532b'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '8d3a304f-b5b1-4f7b-89ce-f74efd75532b'::uuid, 'Etymonline — blessing entry includes ‘blessing in disguise’ recorded from 1746. https://www.etymonline.com/word/blessing', 'https://www.etymonline.com/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '8d3a304f-b5b1-4f7b-89ce-f74efd75532b'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Etymonline — blessing entry includes ‘blessing in disguise’ recorded from 1746. https://www.etymonline.com/word/blessing');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '8d3a304f-b5b1-4f7b-89ce-f74efd75532b'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '8d3a304f-b5b1-4f7b-89ce-f74efd75532b'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '8d3a304f-b5b1-4f7b-89ce-f74efd75532b'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '8d3a304f-b5b1-4f7b-89ce-f74efd75532b'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '8d3a304f-b5b1-4f7b-89ce-f74efd75532b'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '8d3a304f-b5b1-4f7b-89ce-f74efd75532b'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '8d3a304f-b5b1-4f7b-89ce-f74efd75532b'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '8d3a304f-b5b1-4f7b-89ce-f74efd75532b'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');

