-- =============================================================================
-- Phase 9 — Partial remainder (generic pillars; no invented dates)
-- =============================================================================
-- Targets PARTIAL rows not covered by research packs above. Idempotent fills.
-- Generated by scripts/generate-phase9-migrations.js — DO NOT EXECUTE until reviewed.
-- =============================================================================


-- 9b48367f-a7b9-4baf-9ac0-ed7e058daf4a
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = '9b48367f-a7b9-4baf-9ac0-ed7e058daf4a'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = '9b48367f-a7b9-4baf-9ac0-ed7e058daf4a'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '9b48367f-a7b9-4baf-9ac0-ed7e058daf4a'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '9b48367f-a7b9-4baf-9ac0-ed7e058daf4a'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '9b48367f-a7b9-4baf-9ac0-ed7e058daf4a'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '9b48367f-a7b9-4baf-9ac0-ed7e058daf4a'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '9b48367f-a7b9-4baf-9ac0-ed7e058daf4a'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '9b48367f-a7b9-4baf-9ac0-ed7e058daf4a'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '9b48367f-a7b9-4baf-9ac0-ed7e058daf4a'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '9b48367f-a7b9-4baf-9ac0-ed7e058daf4a'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 1e9d46b2-b7c0-4d45-adeb-18b6923cd28c
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = '1e9d46b2-b7c0-4d45-adeb-18b6923cd28c'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = '1e9d46b2-b7c0-4d45-adeb-18b6923cd28c'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '1e9d46b2-b7c0-4d45-adeb-18b6923cd28c'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '1e9d46b2-b7c0-4d45-adeb-18b6923cd28c'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '1e9d46b2-b7c0-4d45-adeb-18b6923cd28c'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '1e9d46b2-b7c0-4d45-adeb-18b6923cd28c'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '1e9d46b2-b7c0-4d45-adeb-18b6923cd28c'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '1e9d46b2-b7c0-4d45-adeb-18b6923cd28c'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '1e9d46b2-b7c0-4d45-adeb-18b6923cd28c'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '1e9d46b2-b7c0-4d45-adeb-18b6923cd28c'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 3824b265-d252-446c-906d-066cf6ac3735
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = '3824b265-d252-446c-906d-066cf6ac3735'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = '3824b265-d252-446c-906d-066cf6ac3735'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '3824b265-d252-446c-906d-066cf6ac3735'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '3824b265-d252-446c-906d-066cf6ac3735'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '3824b265-d252-446c-906d-066cf6ac3735'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '3824b265-d252-446c-906d-066cf6ac3735'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '3824b265-d252-446c-906d-066cf6ac3735'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '3824b265-d252-446c-906d-066cf6ac3735'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '3824b265-d252-446c-906d-066cf6ac3735'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '3824b265-d252-446c-906d-066cf6ac3735'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- c291b113-eba0-4d04-a0dc-ab53a1fe2dbb
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = 'c291b113-eba0-4d04-a0dc-ab53a1fe2dbb'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = 'c291b113-eba0-4d04-a0dc-ab53a1fe2dbb'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'c291b113-eba0-4d04-a0dc-ab53a1fe2dbb'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'c291b113-eba0-4d04-a0dc-ab53a1fe2dbb'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'c291b113-eba0-4d04-a0dc-ab53a1fe2dbb'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'c291b113-eba0-4d04-a0dc-ab53a1fe2dbb'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'c291b113-eba0-4d04-a0dc-ab53a1fe2dbb'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'c291b113-eba0-4d04-a0dc-ab53a1fe2dbb'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'c291b113-eba0-4d04-a0dc-ab53a1fe2dbb'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'c291b113-eba0-4d04-a0dc-ab53a1fe2dbb'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- ea562ce2-5122-47c8-9420-14e218a8745f
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = 'ea562ce2-5122-47c8-9420-14e218a8745f'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = 'ea562ce2-5122-47c8-9420-14e218a8745f'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'ea562ce2-5122-47c8-9420-14e218a8745f'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'ea562ce2-5122-47c8-9420-14e218a8745f'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'ea562ce2-5122-47c8-9420-14e218a8745f'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'ea562ce2-5122-47c8-9420-14e218a8745f'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'ea562ce2-5122-47c8-9420-14e218a8745f'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'ea562ce2-5122-47c8-9420-14e218a8745f'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'ea562ce2-5122-47c8-9420-14e218a8745f'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'ea562ce2-5122-47c8-9420-14e218a8745f'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 7685b795-308d-4f18-8ea6-7fa9ac53259a
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = '7685b795-308d-4f18-8ea6-7fa9ac53259a'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = '7685b795-308d-4f18-8ea6-7fa9ac53259a'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '7685b795-308d-4f18-8ea6-7fa9ac53259a'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '7685b795-308d-4f18-8ea6-7fa9ac53259a'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '7685b795-308d-4f18-8ea6-7fa9ac53259a'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '7685b795-308d-4f18-8ea6-7fa9ac53259a'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '7685b795-308d-4f18-8ea6-7fa9ac53259a'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '7685b795-308d-4f18-8ea6-7fa9ac53259a'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '7685b795-308d-4f18-8ea6-7fa9ac53259a'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '7685b795-308d-4f18-8ea6-7fa9ac53259a'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 19d0cee7-2ea5-41fc-acbb-97042af098b7
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = '19d0cee7-2ea5-41fc-acbb-97042af098b7'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = '19d0cee7-2ea5-41fc-acbb-97042af098b7'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '19d0cee7-2ea5-41fc-acbb-97042af098b7'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '19d0cee7-2ea5-41fc-acbb-97042af098b7'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '19d0cee7-2ea5-41fc-acbb-97042af098b7'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '19d0cee7-2ea5-41fc-acbb-97042af098b7'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '19d0cee7-2ea5-41fc-acbb-97042af098b7'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '19d0cee7-2ea5-41fc-acbb-97042af098b7'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '19d0cee7-2ea5-41fc-acbb-97042af098b7'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '19d0cee7-2ea5-41fc-acbb-97042af098b7'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 0337f822-b606-426d-a988-9ae54a20b7fe
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = '0337f822-b606-426d-a988-9ae54a20b7fe'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = '0337f822-b606-426d-a988-9ae54a20b7fe'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '0337f822-b606-426d-a988-9ae54a20b7fe'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '0337f822-b606-426d-a988-9ae54a20b7fe'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '0337f822-b606-426d-a988-9ae54a20b7fe'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '0337f822-b606-426d-a988-9ae54a20b7fe'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '0337f822-b606-426d-a988-9ae54a20b7fe'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '0337f822-b606-426d-a988-9ae54a20b7fe'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '0337f822-b606-426d-a988-9ae54a20b7fe'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '0337f822-b606-426d-a988-9ae54a20b7fe'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 5cdfffba-a5fe-44b7-867b-038b2315e0f4
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = '5cdfffba-a5fe-44b7-867b-038b2315e0f4'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = '5cdfffba-a5fe-44b7-867b-038b2315e0f4'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '5cdfffba-a5fe-44b7-867b-038b2315e0f4'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '5cdfffba-a5fe-44b7-867b-038b2315e0f4'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '5cdfffba-a5fe-44b7-867b-038b2315e0f4'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '5cdfffba-a5fe-44b7-867b-038b2315e0f4'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '5cdfffba-a5fe-44b7-867b-038b2315e0f4'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '5cdfffba-a5fe-44b7-867b-038b2315e0f4'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '5cdfffba-a5fe-44b7-867b-038b2315e0f4'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '5cdfffba-a5fe-44b7-867b-038b2315e0f4'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- f3406d1e-c8e1-4803-9f7c-9d480ea93ed2
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = 'f3406d1e-c8e1-4803-9f7c-9d480ea93ed2'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = 'f3406d1e-c8e1-4803-9f7c-9d480ea93ed2'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'f3406d1e-c8e1-4803-9f7c-9d480ea93ed2'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'f3406d1e-c8e1-4803-9f7c-9d480ea93ed2'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'f3406d1e-c8e1-4803-9f7c-9d480ea93ed2'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'f3406d1e-c8e1-4803-9f7c-9d480ea93ed2'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'f3406d1e-c8e1-4803-9f7c-9d480ea93ed2'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'f3406d1e-c8e1-4803-9f7c-9d480ea93ed2'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'f3406d1e-c8e1-4803-9f7c-9d480ea93ed2'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'f3406d1e-c8e1-4803-9f7c-9d480ea93ed2'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 6262445f-75ae-4808-8169-c90dfddf8926
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = '6262445f-75ae-4808-8169-c90dfddf8926'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = '6262445f-75ae-4808-8169-c90dfddf8926'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '6262445f-75ae-4808-8169-c90dfddf8926'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '6262445f-75ae-4808-8169-c90dfddf8926'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '6262445f-75ae-4808-8169-c90dfddf8926'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '6262445f-75ae-4808-8169-c90dfddf8926'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '6262445f-75ae-4808-8169-c90dfddf8926'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '6262445f-75ae-4808-8169-c90dfddf8926'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '6262445f-75ae-4808-8169-c90dfddf8926'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '6262445f-75ae-4808-8169-c90dfddf8926'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- b7687049-bfe0-42b2-84d7-919383741e66
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = 'b7687049-bfe0-42b2-84d7-919383741e66'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = 'b7687049-bfe0-42b2-84d7-919383741e66'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'b7687049-bfe0-42b2-84d7-919383741e66'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'b7687049-bfe0-42b2-84d7-919383741e66'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'b7687049-bfe0-42b2-84d7-919383741e66'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'b7687049-bfe0-42b2-84d7-919383741e66'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'b7687049-bfe0-42b2-84d7-919383741e66'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'b7687049-bfe0-42b2-84d7-919383741e66'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'b7687049-bfe0-42b2-84d7-919383741e66'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'b7687049-bfe0-42b2-84d7-919383741e66'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- c068b111-e3eb-49b8-8c15-8f6977b8f553
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = 'c068b111-e3eb-49b8-8c15-8f6977b8f553'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = 'c068b111-e3eb-49b8-8c15-8f6977b8f553'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'c068b111-e3eb-49b8-8c15-8f6977b8f553'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'c068b111-e3eb-49b8-8c15-8f6977b8f553'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'c068b111-e3eb-49b8-8c15-8f6977b8f553'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'c068b111-e3eb-49b8-8c15-8f6977b8f553'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'c068b111-e3eb-49b8-8c15-8f6977b8f553'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'c068b111-e3eb-49b8-8c15-8f6977b8f553'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'c068b111-e3eb-49b8-8c15-8f6977b8f553'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'c068b111-e3eb-49b8-8c15-8f6977b8f553'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 35c78bb9-5a8f-4ee4-9fad-ff21ac23563b
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = '35c78bb9-5a8f-4ee4-9fad-ff21ac23563b'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = '35c78bb9-5a8f-4ee4-9fad-ff21ac23563b'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '35c78bb9-5a8f-4ee4-9fad-ff21ac23563b'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '35c78bb9-5a8f-4ee4-9fad-ff21ac23563b'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '35c78bb9-5a8f-4ee4-9fad-ff21ac23563b'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '35c78bb9-5a8f-4ee4-9fad-ff21ac23563b'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '35c78bb9-5a8f-4ee4-9fad-ff21ac23563b'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '35c78bb9-5a8f-4ee4-9fad-ff21ac23563b'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '35c78bb9-5a8f-4ee4-9fad-ff21ac23563b'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '35c78bb9-5a8f-4ee4-9fad-ff21ac23563b'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 91ff76ae-f6c4-425a-9f0e-cfad51fd4a12
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = '91ff76ae-f6c4-425a-9f0e-cfad51fd4a12'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = '91ff76ae-f6c4-425a-9f0e-cfad51fd4a12'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '91ff76ae-f6c4-425a-9f0e-cfad51fd4a12'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '91ff76ae-f6c4-425a-9f0e-cfad51fd4a12'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '91ff76ae-f6c4-425a-9f0e-cfad51fd4a12'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '91ff76ae-f6c4-425a-9f0e-cfad51fd4a12'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '91ff76ae-f6c4-425a-9f0e-cfad51fd4a12'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '91ff76ae-f6c4-425a-9f0e-cfad51fd4a12'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '91ff76ae-f6c4-425a-9f0e-cfad51fd4a12'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '91ff76ae-f6c4-425a-9f0e-cfad51fd4a12'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 4c079a37-723c-44d7-9129-ca463d8c4c79
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = '4c079a37-723c-44d7-9129-ca463d8c4c79'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = '4c079a37-723c-44d7-9129-ca463d8c4c79'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '4c079a37-723c-44d7-9129-ca463d8c4c79'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '4c079a37-723c-44d7-9129-ca463d8c4c79'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '4c079a37-723c-44d7-9129-ca463d8c4c79'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '4c079a37-723c-44d7-9129-ca463d8c4c79'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '4c079a37-723c-44d7-9129-ca463d8c4c79'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '4c079a37-723c-44d7-9129-ca463d8c4c79'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '4c079a37-723c-44d7-9129-ca463d8c4c79'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '4c079a37-723c-44d7-9129-ca463d8c4c79'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- f3e5c682-0bf3-49c0-9402-a1338e7adafc
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = 'f3e5c682-0bf3-49c0-9402-a1338e7adafc'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = 'f3e5c682-0bf3-49c0-9402-a1338e7adafc'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'f3e5c682-0bf3-49c0-9402-a1338e7adafc'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'f3e5c682-0bf3-49c0-9402-a1338e7adafc'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'f3e5c682-0bf3-49c0-9402-a1338e7adafc'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'f3e5c682-0bf3-49c0-9402-a1338e7adafc'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'f3e5c682-0bf3-49c0-9402-a1338e7adafc'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'f3e5c682-0bf3-49c0-9402-a1338e7adafc'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'f3e5c682-0bf3-49c0-9402-a1338e7adafc'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'f3e5c682-0bf3-49c0-9402-a1338e7adafc'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- f444c9d2-7af6-47ca-850a-bce7116bf4ec
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = 'f444c9d2-7af6-47ca-850a-bce7116bf4ec'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = 'f444c9d2-7af6-47ca-850a-bce7116bf4ec'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'f444c9d2-7af6-47ca-850a-bce7116bf4ec'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'f444c9d2-7af6-47ca-850a-bce7116bf4ec'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'f444c9d2-7af6-47ca-850a-bce7116bf4ec'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'f444c9d2-7af6-47ca-850a-bce7116bf4ec'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'f444c9d2-7af6-47ca-850a-bce7116bf4ec'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'f444c9d2-7af6-47ca-850a-bce7116bf4ec'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'f444c9d2-7af6-47ca-850a-bce7116bf4ec'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'f444c9d2-7af6-47ca-850a-bce7116bf4ec'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 245f0a58-fd91-4c80-9aba-7be8870a660c
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = '245f0a58-fd91-4c80-9aba-7be8870a660c'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = '245f0a58-fd91-4c80-9aba-7be8870a660c'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '245f0a58-fd91-4c80-9aba-7be8870a660c'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '245f0a58-fd91-4c80-9aba-7be8870a660c'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '245f0a58-fd91-4c80-9aba-7be8870a660c'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '245f0a58-fd91-4c80-9aba-7be8870a660c'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '245f0a58-fd91-4c80-9aba-7be8870a660c'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '245f0a58-fd91-4c80-9aba-7be8870a660c'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '245f0a58-fd91-4c80-9aba-7be8870a660c'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '245f0a58-fd91-4c80-9aba-7be8870a660c'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 6b330bba-29b9-4f62-a708-1e4eb1786af2
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = '6b330bba-29b9-4f62-a708-1e4eb1786af2'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = '6b330bba-29b9-4f62-a708-1e4eb1786af2'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '6b330bba-29b9-4f62-a708-1e4eb1786af2'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '6b330bba-29b9-4f62-a708-1e4eb1786af2'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '6b330bba-29b9-4f62-a708-1e4eb1786af2'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '6b330bba-29b9-4f62-a708-1e4eb1786af2'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '6b330bba-29b9-4f62-a708-1e4eb1786af2'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '6b330bba-29b9-4f62-a708-1e4eb1786af2'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '6b330bba-29b9-4f62-a708-1e4eb1786af2'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '6b330bba-29b9-4f62-a708-1e4eb1786af2'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 4a1c5d67-a816-45a8-80c7-857ce561ae4d
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = '4a1c5d67-a816-45a8-80c7-857ce561ae4d'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = '4a1c5d67-a816-45a8-80c7-857ce561ae4d'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '4a1c5d67-a816-45a8-80c7-857ce561ae4d'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '4a1c5d67-a816-45a8-80c7-857ce561ae4d'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '4a1c5d67-a816-45a8-80c7-857ce561ae4d'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '4a1c5d67-a816-45a8-80c7-857ce561ae4d'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '4a1c5d67-a816-45a8-80c7-857ce561ae4d'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '4a1c5d67-a816-45a8-80c7-857ce561ae4d'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '4a1c5d67-a816-45a8-80c7-857ce561ae4d'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '4a1c5d67-a816-45a8-80c7-857ce561ae4d'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- bbc2c25d-d6ff-44b6-a212-c0182f6e6e82
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = 'bbc2c25d-d6ff-44b6-a212-c0182f6e6e82'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = 'bbc2c25d-d6ff-44b6-a212-c0182f6e6e82'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'bbc2c25d-d6ff-44b6-a212-c0182f6e6e82'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'bbc2c25d-d6ff-44b6-a212-c0182f6e6e82'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'bbc2c25d-d6ff-44b6-a212-c0182f6e6e82'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'bbc2c25d-d6ff-44b6-a212-c0182f6e6e82'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'bbc2c25d-d6ff-44b6-a212-c0182f6e6e82'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'bbc2c25d-d6ff-44b6-a212-c0182f6e6e82'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'bbc2c25d-d6ff-44b6-a212-c0182f6e6e82'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'bbc2c25d-d6ff-44b6-a212-c0182f6e6e82'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- a86e2fed-ea76-4db9-8461-b1f8115cee89
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = 'a86e2fed-ea76-4db9-8461-b1f8115cee89'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = 'a86e2fed-ea76-4db9-8461-b1f8115cee89'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'a86e2fed-ea76-4db9-8461-b1f8115cee89'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'a86e2fed-ea76-4db9-8461-b1f8115cee89'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'a86e2fed-ea76-4db9-8461-b1f8115cee89'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'a86e2fed-ea76-4db9-8461-b1f8115cee89'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'a86e2fed-ea76-4db9-8461-b1f8115cee89'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'a86e2fed-ea76-4db9-8461-b1f8115cee89'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'a86e2fed-ea76-4db9-8461-b1f8115cee89'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'a86e2fed-ea76-4db9-8461-b1f8115cee89'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- cb96b070-e1c4-4bf5-82f0-031135d1c134
UPDATE adages SET
  etymology = COALESCE(etymology, 'The saying compresses everyday judgment into a short, memorable line; wording is traditional rather than technical.'),
  historical_context = COALESCE(historical_context, 'Circulates in speech, schools, workplaces, and media as a shorthand for practical wisdom.'),
  interpretation = COALESCE(interpretation, 'Read it as a rule of thumb: useful orientation, not a universal law without context.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when coaching, planning, or mediating—pair with specifics rather than treating the line as proof.'),
  origin = CASE
    WHEN length(trim(coalesce(origin, ''))) < 60 THEN
      COALESCE(NULLIF(trim(origin), ''), 'Origin uncertain; traditional proverb/idiom in modern English usage.')
    ELSE origin
  END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Exact earliest attestation not yet pinned; widely circulating in modern English.'),
  updated_at = now()
WHERE id = 'cb96b070-e1c4-4bf5-82f0-031135d1c134'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['wisdom', 'observation']))
) WHERE id = 'cb96b070-e1c4-4bf5-82f0-031135d1c134'::uuid AND deleted_at IS NULL;

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'cb96b070-e1c4-4bf5-82f0-031135d1c134'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'cb96b070-e1c4-4bf5-82f0-031135d1c134'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'cb96b070-e1c4-4bf5-82f0-031135d1c134'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'cb96b070-e1c4-4bf5-82f0-031135d1c134'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'cb96b070-e1c4-4bf5-82f0-031135d1c134'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'cb96b070-e1c4-4bf5-82f0-031135d1c134'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'cb96b070-e1c4-4bf5-82f0-031135d1c134'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'cb96b070-e1c4-4bf5-82f0-031135d1c134'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');

