-- =============================================================================
-- Phase 9 — Attribution-sensitive English (quotes / tricky attributions)
-- =============================================================================
-- Generated by scripts/generate-phase9-migrations.js — DO NOT EXECUTE until reviewed.
-- =============================================================================


-- bc4eec09-21b8-4415-a156-0b893124dd25 — Better to light a candle than curse the darkness
UPDATE adages SET
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Earliest located appearance is 1907, in a sermon collection by William L. Watkinson; later circulation led to “Chinese proverb / Confucius” attributions that are not supported by evidence.' ELSE origin END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), '1907 (earliest located), then widely recirculated in religious and political rhetoric.'),
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = 'bc4eec09-21b8-4415-a156-0b893124dd25'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['English', 'idiom', 'action', 'advocacy']))
) WHERE id = 'bc4eec09-21b8-4415-a156-0b893124dd25'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT 'bc4eec09-21b8-4415-a156-0b893124dd25'::uuid, 'Quote Investigator — earliest located usage (1907 Watkinson) + discussion of misattribution. https://quoteinvestigator.com/2017/03/19/candle/', 'https://quoteinvestigator.com/2017/03/19/candle/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = 'bc4eec09-21b8-4415-a156-0b893124dd25'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Quote Investigator — earliest located usage (1907 Watkinson) + discussion of misattribution. https://quoteinvestigator.com/2017/03/19/candle/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'bc4eec09-21b8-4415-a156-0b893124dd25'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'bc4eec09-21b8-4415-a156-0b893124dd25'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'bc4eec09-21b8-4415-a156-0b893124dd25'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'bc4eec09-21b8-4415-a156-0b893124dd25'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'bc4eec09-21b8-4415-a156-0b893124dd25'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'bc4eec09-21b8-4415-a156-0b893124dd25'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'bc4eec09-21b8-4415-a156-0b893124dd25'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'bc4eec09-21b8-4415-a156-0b893124dd25'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 80129a50-7c8b-4754-bdd7-793ef53509fb — The squeaky wheel gets the grease
UPDATE adages SET
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Earliest modern-form evidence located is 1903 in Cal Stewart/Josh Weathersby verse; later misattributed in quotation books.' ELSE origin END,
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = '80129a50-7c8b-4754-bdd7-793ef53509fb'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['American English', 'idiom', 'attention', 'advocacy']))
) WHERE id = '80129a50-7c8b-4754-bdd7-793ef53509fb'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '80129a50-7c8b-4754-bdd7-793ef53509fb'::uuid, 'Quote Investigator — squeaky wheel origin trace (1903 Cal Stewart). https://quoteinvestigator.com/2012/12/26/squeaky-wheel/', 'https://quoteinvestigator.com/2012/12/26/squeaky-wheel/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '80129a50-7c8b-4754-bdd7-793ef53509fb'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Quote Investigator — squeaky wheel origin trace (1903 Cal Stewart). https://quoteinvestigator.com/2012/12/26/squeaky-wheel/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '80129a50-7c8b-4754-bdd7-793ef53509fb'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '80129a50-7c8b-4754-bdd7-793ef53509fb'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '80129a50-7c8b-4754-bdd7-793ef53509fb'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '80129a50-7c8b-4754-bdd7-793ef53509fb'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '80129a50-7c8b-4754-bdd7-793ef53509fb'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '80129a50-7c8b-4754-bdd7-793ef53509fb'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '80129a50-7c8b-4754-bdd7-793ef53509fb'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '80129a50-7c8b-4754-bdd7-793ef53509fb'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- c11d47fc-f3db-44c8-8df1-3aa12ab06fc8 — Even a stopped clock is right twice a day
UPDATE adages SET
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Earliest located match is 1711 in The Spectator (Addison); later reused by many authors.' ELSE origin END,
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = 'c11d47fc-f3db-44c8-8df1-3aa12ab06fc8'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['English', 'idiom', 'error', 'time']))
) WHERE id = 'c11d47fc-f3db-44c8-8df1-3aa12ab06fc8'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT 'c11d47fc-f3db-44c8-8df1-3aa12ab06fc8'::uuid, 'Quote Investigator — stopped clock origin trace (1711 The Spectator/Addison). https://quoteinvestigator.com/2016/09/02/stopped-clock/', 'https://quoteinvestigator.com/2016/09/02/stopped-clock/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = 'c11d47fc-f3db-44c8-8df1-3aa12ab06fc8'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Quote Investigator — stopped clock origin trace (1711 The Spectator/Addison). https://quoteinvestigator.com/2016/09/02/stopped-clock/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'c11d47fc-f3db-44c8-8df1-3aa12ab06fc8'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'c11d47fc-f3db-44c8-8df1-3aa12ab06fc8'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'c11d47fc-f3db-44c8-8df1-3aa12ab06fc8'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'c11d47fc-f3db-44c8-8df1-3aa12ab06fc8'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'c11d47fc-f3db-44c8-8df1-3aa12ab06fc8'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'c11d47fc-f3db-44c8-8df1-3aa12ab06fc8'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'c11d47fc-f3db-44c8-8df1-3aa12ab06fc8'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'c11d47fc-f3db-44c8-8df1-3aa12ab06fc8'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 3e4b4736-ddbd-4fe1-a06f-ea0ee00ca3e0 — The operation was a success, but the patient died
UPDATE adages SET
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Documented as an old medical joke; cited in print since at least 1829 (newspaper excerpt).' ELSE origin END,
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = '3e4b4736-ddbd-4fe1-a06f-ea0ee00ca3e0'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['English', 'idiom', 'systems', 'ethics']))
) WHERE id = '3e4b4736-ddbd-4fe1-a06f-ea0ee00ca3e0'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '3e4b4736-ddbd-4fe1-a06f-ea0ee00ca3e0'::uuid, 'Barry Popik — earliest print citations (1829). https://barrypopik.com/blog/the_operation_was_successful_but_the_patient_died', 'https://barrypopik.com/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '3e4b4736-ddbd-4fe1-a06f-ea0ee00ca3e0'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Barry Popik — earliest print citations (1829). https://barrypopik.com/blog/the_operation_was_successful_but_the_patient_died');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '3e4b4736-ddbd-4fe1-a06f-ea0ee00ca3e0'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '3e4b4736-ddbd-4fe1-a06f-ea0ee00ca3e0'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '3e4b4736-ddbd-4fe1-a06f-ea0ee00ca3e0'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '3e4b4736-ddbd-4fe1-a06f-ea0ee00ca3e0'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '3e4b4736-ddbd-4fe1-a06f-ea0ee00ca3e0'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '3e4b4736-ddbd-4fe1-a06f-ea0ee00ca3e0'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '3e4b4736-ddbd-4fe1-a06f-ea0ee00ca3e0'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '3e4b4736-ddbd-4fe1-a06f-ea0ee00ca3e0'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- b96cdc3c-1159-40c0-acb1-69cdfc8364c4 — A rising tide lifts all boats
UPDATE adages SET
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Popularized in US political rhetoric; confirmed in JFK speech transcripts (1960) and preserved public remarks (1963). Avoid claiming a single inventor.' ELSE origin END,
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = 'b96cdc3c-1159-40c0-acb1-69cdfc8364c4'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['American English', 'idiom', 'economics', 'leadership']))
) WHERE id = 'b96cdc3c-1159-40c0-acb1-69cdfc8364c4'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT 'b96cdc3c-1159-40c0-acb1-69cdfc8364c4'::uuid, 'JFK Library speech transcript (1960) containing phrase. https://www.jfklibrary.org/', 'https://www.jfklibrary.org/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = 'b96cdc3c-1159-40c0-acb1-69cdfc8364c4'::uuid AND c.deleted_at IS NULL AND c.source_text = 'JFK Library speech transcript (1960) containing phrase. https://www.jfklibrary.org/');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT 'b96cdc3c-1159-40c0-acb1-69cdfc8364c4'::uuid, 'The American Presidency Project — 1963 remarks containing phrase. https://www.presidency.ucsb.edu/', 'https://www.presidency.ucsb.edu/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = 'b96cdc3c-1159-40c0-acb1-69cdfc8364c4'::uuid AND c.deleted_at IS NULL AND c.source_text = 'The American Presidency Project — 1963 remarks containing phrase. https://www.presidency.ucsb.edu/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'b96cdc3c-1159-40c0-acb1-69cdfc8364c4'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'b96cdc3c-1159-40c0-acb1-69cdfc8364c4'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'b96cdc3c-1159-40c0-acb1-69cdfc8364c4'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'b96cdc3c-1159-40c0-acb1-69cdfc8364c4'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'b96cdc3c-1159-40c0-acb1-69cdfc8364c4'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'b96cdc3c-1159-40c0-acb1-69cdfc8364c4'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'b96cdc3c-1159-40c0-acb1-69cdfc8364c4'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'b96cdc3c-1159-40c0-acb1-69cdfc8364c4'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 72017c70-b166-42f3-859d-a8c7fc663314 — Laugh, and the world laughs with you
UPDATE adages SET
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Poem “Solitude” by Ella Wheeler Wilcox; commonly quoted as an aphorism.' ELSE origin END,
  etymology = COALESCE(etymology, 'Metaphorical speech: familiar imagery carries moral weight beyond literal wording; read for sense, not etymological literalism.'),
  historical_context = COALESCE(historical_context, 'Circulates through sermons, speeches, journalism, and social media; attribution debates are common.'),
  interpretation = COALESCE(interpretation, 'Treat the line as a practical prompt; context still decides proportion and fairness.'),
  modern_practicality = COALESCE(modern_practicality, 'Useful when motivating action, auditing incentives, or critiquing fatalism—pair with evidence.'),
  updated_at = now()
WHERE id = '72017c70-b166-42f3-859d-a8c7fc663314'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['English', 'idiom', 'character', 'speech']))
) WHERE id = '72017c70-b166-42f3-859d-a8c7fc663314'::uuid AND deleted_at IS NULL;
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '72017c70-b166-42f3-859d-a8c7fc663314'::uuid, 'Poetry Foundation — Solitude (Ella Wheeler Wilcox). https://www.poetryfoundation.org/', 'https://www.poetryfoundation.org/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '72017c70-b166-42f3-859d-a8c7fc663314'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Poetry Foundation — Solitude (Ella Wheeler Wilcox). https://www.poetryfoundation.org/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '72017c70-b166-42f3-859d-a8c7fc663314'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '72017c70-b166-42f3-859d-a8c7fc663314'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '72017c70-b166-42f3-859d-a8c7fc663314'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '72017c70-b166-42f3-859d-a8c7fc663314'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '72017c70-b166-42f3-859d-a8c7fc663314'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '72017c70-b166-42f3-859d-a8c7fc663314'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '72017c70-b166-42f3-859d-a8c7fc663314'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '72017c70-b166-42f3-859d-a8c7fc663314'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');

