-- =============================================================================
-- Phase 9 — Non-English origins (Chinese / Japanese / Latin)
-- =============================================================================
-- Generated by scripts/generate-phase9-migrations.js — DO NOT EXECUTE until reviewed.
-- =============================================================================


-- 4cb28a07-f387-4950-96ca-017b74bafc03 — Covering ears to steal a bell
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'Using self-deception to make wrongdoing feel “safe”; trying to hide a fault by refusing to acknowledge reality.' ELSE definition END,
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Traditional Chinese chengyu. Modern idiom references treat it as a classical anecdote; avoid claiming a single author.' ELSE origin END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Classical/early literary provenance noted in standard idiom references; English renderings vary.'),
  etymology = COALESCE(etymology, 'Literally “cover ears, steal bell”—the joke is that blocking your own hearing doesn’t block others’ awareness.'),
  historical_context = COALESCE(historical_context, 'Often used to criticize denial, rationalization, and willful blindness in governance or personal conduct.'),
  interpretation = COALESCE(interpretation, 'If you only “trick yourself,” the world does not change; consequences remain external.'),
  modern_practicality = COALESCE(modern_practicality, 'Use it as a warning to seek outside feedback and reality-checks when you feel tempted to ignore obvious signals.'),
  updated_at = now()
WHERE id = '4cb28a07-f387-4950-96ca-017b74bafc03'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['Chinese', 'idiom', 'behavior', 'wisdom']))
) WHERE id = '4cb28a07-f387-4950-96ca-017b74bafc03'::uuid AND deleted_at IS NULL;
INSERT INTO adage_translations (adage_id, language_code, translated_text, translator_notes)
SELECT '4cb28a07-f387-4950-96ca-017b74bafc03'::uuid, 'zh', '掩耳盜鈴', 'pinyin: yǎn ěr dào líng'
WHERE NOT EXISTS (SELECT 1 FROM adage_translations t WHERE t.adage_id = '4cb28a07-f387-4950-96ca-017b74bafc03'::uuid AND t.deleted_at IS NULL AND t.language_code = 'zh');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '4cb28a07-f387-4950-96ca-017b74bafc03'::uuid, 'Taiwan Ministry of Education Idioms Dictionary — 掩耳盜鈴 (meaning +典故). https://dict.idioms.moe.edu.tw/', 'https://dict.idioms.moe.edu.tw/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '4cb28a07-f387-4950-96ca-017b74bafc03'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Taiwan Ministry of Education Idioms Dictionary — 掩耳盜鈴 (meaning +典故). https://dict.idioms.moe.edu.tw/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '4cb28a07-f387-4950-96ca-017b74bafc03'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '4cb28a07-f387-4950-96ca-017b74bafc03'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '4cb28a07-f387-4950-96ca-017b74bafc03'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '4cb28a07-f387-4950-96ca-017b74bafc03'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '4cb28a07-f387-4950-96ca-017b74bafc03'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '4cb28a07-f387-4950-96ca-017b74bafc03'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '4cb28a07-f387-4950-96ca-017b74bafc03'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '4cb28a07-f387-4950-96ca-017b74bafc03'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- e315ea0d-d29b-427a-a9dd-520a7208d12f — A frog in a well shaft
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'A narrow worldview mistaken for the whole; someone whose experience is too limited to judge confidently.' ELSE definition END,
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Traditional Chinese idiom; provenance described in idiom references.' ELSE origin END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Traditional Chinese idiom; provenance described in idiom references.'),
  etymology = COALESCE(etymology, '“Frog at the bottom of a well” can only see a small patch of sky.'),
  historical_context = COALESCE(historical_context, 'Used in education and debate as a critique of overconfidence built on limited exposure.'),
  interpretation = COALESCE(interpretation, 'Humility rises when you acknowledge the size of the world beyond your “well.”'),
  modern_practicality = COALESCE(modern_practicality, 'Seek wider inputs (other cultures, disciplines, lived experiences) before forming sweeping conclusions.'),
  updated_at = now()
WHERE id = 'e315ea0d-d29b-427a-a9dd-520a7208d12f'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['Chinese', 'idiom', 'learning', 'judgment']))
) WHERE id = 'e315ea0d-d29b-427a-a9dd-520a7208d12f'::uuid AND deleted_at IS NULL;
INSERT INTO adage_translations (adage_id, language_code, translated_text, translator_notes)
SELECT 'e315ea0d-d29b-427a-a9dd-520a7208d12f'::uuid, 'zh', '井底之蛙', 'pinyin: jǐng dǐ zhī wā'
WHERE NOT EXISTS (SELECT 1 FROM adage_translations t WHERE t.adage_id = 'e315ea0d-d29b-427a-a9dd-520a7208d12f'::uuid AND t.deleted_at IS NULL AND t.language_code = 'zh');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT 'e315ea0d-d29b-427a-a9dd-520a7208d12f'::uuid, 'Taiwan Ministry of Education Idioms Dictionary — 井底之蛙. https://dict.idioms.moe.edu.tw/', 'https://dict.idioms.moe.edu.tw/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = 'e315ea0d-d29b-427a-a9dd-520a7208d12f'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Taiwan Ministry of Education Idioms Dictionary — 井底之蛙. https://dict.idioms.moe.edu.tw/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'e315ea0d-d29b-427a-a9dd-520a7208d12f'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'e315ea0d-d29b-427a-a9dd-520a7208d12f'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'e315ea0d-d29b-427a-a9dd-520a7208d12f'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'e315ea0d-d29b-427a-a9dd-520a7208d12f'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'e315ea0d-d29b-427a-a9dd-520a7208d12f'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'e315ea0d-d29b-427a-a9dd-520a7208d12f'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'e315ea0d-d29b-427a-a9dd-520a7208d12f'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'e315ea0d-d29b-427a-a9dd-520a7208d12f'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- fbf30565-8315-419b-bc7c-34e4e599f127 — Dream different dreams on the same bed
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'People appear aligned (same home/plan/team) but pursue different ends or hold incompatible intentions.' ELSE definition END,
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Traditional Chinese idiom; provenance in education/idiom references.' ELSE origin END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Traditional Chinese idiom; provenance in education/idiom references.'),
  etymology = COALESCE(etymology, '“Same bed, different dreams” highlights private intention beneath shared circumstances.'),
  historical_context = COALESCE(historical_context, 'Common in politics, partnerships, and coalition talk when unity is more performative than real.'),
  interpretation = COALESCE(interpretation, 'Shared space does not guarantee shared purpose.'),
  modern_practicality = COALESCE(modern_practicality, 'Clarify goals and incentives early; don’t confuse agreement-in-public with alignment-in-private.'),
  updated_at = now()
WHERE id = 'fbf30565-8315-419b-bc7c-34e4e599f127'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['Chinese', 'idiom', 'conflict', 'trust']))
) WHERE id = 'fbf30565-8315-419b-bc7c-34e4e599f127'::uuid AND deleted_at IS NULL;
INSERT INTO adage_translations (adage_id, language_code, translated_text, translator_notes)
SELECT 'fbf30565-8315-419b-bc7c-34e4e599f127'::uuid, 'zh', '同床異夢', 'pinyin: tóng chuáng yì mèng'
WHERE NOT EXISTS (SELECT 1 FROM adage_translations t WHERE t.adage_id = 'fbf30565-8315-419b-bc7c-34e4e599f127'::uuid AND t.deleted_at IS NULL AND t.language_code = 'zh');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT 'fbf30565-8315-419b-bc7c-34e4e599f127'::uuid, 'Taiwan Ministry of Education Idioms Dictionary — 同床異夢. https://dict.idioms.moe.edu.tw/', 'https://dict.idioms.moe.edu.tw/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = 'fbf30565-8315-419b-bc7c-34e4e599f127'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Taiwan Ministry of Education Idioms Dictionary — 同床異夢. https://dict.idioms.moe.edu.tw/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'fbf30565-8315-419b-bc7c-34e4e599f127'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'fbf30565-8315-419b-bc7c-34e4e599f127'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'fbf30565-8315-419b-bc7c-34e4e599f127'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'fbf30565-8315-419b-bc7c-34e4e599f127'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'fbf30565-8315-419b-bc7c-34e4e599f127'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'fbf30565-8315-419b-bc7c-34e4e599f127'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'fbf30565-8315-419b-bc7c-34e4e599f127'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'fbf30565-8315-419b-bc7c-34e4e599f127'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 0cfe810f-ea63-4b84-91f4-f63749bcf9df — A thief calls, stop thief
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'A wrongdoer shifts attention by accusing others first; projection used as cover.' ELSE definition END,
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Traditional Chinese idiom; standard idiom references explain meaning/provenance.' ELSE origin END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Classical/literary background summarized in encyclopedia entries; English paraphrases vary.'),
  etymology = COALESCE(etymology, '“Thief shouts ‘catch the thief!’”'),
  historical_context = COALESCE(historical_context, 'Used in political rhetoric and scandal coverage when attackers mirror the behavior they denounce.'),
  interpretation = COALESCE(interpretation, 'Accusations can be tactical; verify before you join a pile-on.'),
  modern_practicality = COALESCE(modern_practicality, 'When blame arrives fast, ask: who benefits from redirecting scrutiny?'),
  updated_at = now()
WHERE id = '0cfe810f-ea63-4b84-91f4-f63749bcf9df'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['Chinese', 'idiom', 'blame', 'ethics']))
) WHERE id = '0cfe810f-ea63-4b84-91f4-f63749bcf9df'::uuid AND deleted_at IS NULL;
INSERT INTO adage_translations (adage_id, language_code, translated_text, translator_notes)
SELECT '0cfe810f-ea63-4b84-91f4-f63749bcf9df'::uuid, 'zh', '賊喊捉賊', 'pinyin: zéi hǎn zhuō zéi'
WHERE NOT EXISTS (SELECT 1 FROM adage_translations t WHERE t.adage_id = '0cfe810f-ea63-4b84-91f4-f63749bcf9df'::uuid AND t.deleted_at IS NULL AND t.language_code = 'zh');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '0cfe810f-ea63-4b84-91f4-f63749bcf9df'::uuid, 'Taiwan MoE Education Encyclopedia — 賊喊捉賊. https://pedia.cloud.edu.tw/', 'https://pedia.cloud.edu.tw/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '0cfe810f-ea63-4b84-91f4-f63749bcf9df'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Taiwan MoE Education Encyclopedia — 賊喊捉賊. https://pedia.cloud.edu.tw/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '0cfe810f-ea63-4b84-91f4-f63749bcf9df'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '0cfe810f-ea63-4b84-91f4-f63749bcf9df'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '0cfe810f-ea63-4b84-91f4-f63749bcf9df'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '0cfe810f-ea63-4b84-91f4-f63749bcf9df'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '0cfe810f-ea63-4b84-91f4-f63749bcf9df'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '0cfe810f-ea63-4b84-91f4-f63749bcf9df'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '0cfe810f-ea63-4b84-91f4-f63749bcf9df'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '0cfe810f-ea63-4b84-91f4-f63749bcf9df'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- e27963e6-d524-4c10-bb94-4ab1483a8083 — Crows everywhere are equally black
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'Cynical claim that “they’re all the same”; often implying widespread corruption or vice.' ELSE definition END,
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Chinese proverb usage; avoid claiming a single originator.' ELSE origin END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Circulates in modern Chinese and English quotation; exact earliest attestation varies by reference work.'),
  etymology = COALESCE(etymology, 'The image compares uniform appearance (black crows) to a blanket moral claim about groups.'),
  historical_context = COALESCE(historical_context, 'Used in moral talk and criticism of institutions; tone can be unfair if over-generalized.'),
  interpretation = COALESCE(interpretation, 'Allegations of sameness are rhetorical; they may obscure real variation among cases.'),
  modern_practicality = COALESCE(modern_practicality, 'When you hear totalizing claims, look for counterexamples, incentives, and evidence.'),
  updated_at = now()
WHERE id = 'e27963e6-d524-4c10-bb94-4ab1483a8083'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['Chinese', 'idiom', 'cynicism', 'judgment']))
) WHERE id = 'e27963e6-d524-4c10-bb94-4ab1483a8083'::uuid AND deleted_at IS NULL;
INSERT INTO adage_translations (adage_id, language_code, translated_text, translator_notes)
SELECT 'e27963e6-d524-4c10-bb94-4ab1483a8083'::uuid, 'zh', '天下烏鴉一般黑', ' '
WHERE NOT EXISTS (SELECT 1 FROM adage_translations t WHERE t.adage_id = 'e27963e6-d524-4c10-bb94-4ab1483a8083'::uuid AND t.deleted_at IS NULL AND t.language_code = 'zh');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT 'e27963e6-d524-4c10-bb94-4ab1483a8083'::uuid, 'Zdic / Chinese proverb reference — 天下乌鸦一般黑 (meaning/usage). https://www.zdic.net/', 'https://www.zdic.net/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = 'e27963e6-d524-4c10-bb94-4ab1483a8083'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Zdic / Chinese proverb reference — 天下乌鸦一般黑 (meaning/usage). https://www.zdic.net/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'e27963e6-d524-4c10-bb94-4ab1483a8083'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'e27963e6-d524-4c10-bb94-4ab1483a8083'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'e27963e6-d524-4c10-bb94-4ab1483a8083'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'e27963e6-d524-4c10-bb94-4ab1483a8083'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'e27963e6-d524-4c10-bb94-4ab1483a8083'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'e27963e6-d524-4c10-bb94-4ab1483a8083'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'e27963e6-d524-4c10-bb94-4ab1483a8083'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'e27963e6-d524-4c10-bb94-4ab1483a8083'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 2b4fb088-80e2-4d68-b90b-7daa57f3b043 — Scratching an itch from outside the boot
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'Trying to solve a problem indirectly so the real issue never gets addressed.' ELSE definition END,
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Traditional Chinese chengyu; meaning explained in standard idiom references.' ELSE origin END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Classical/literary background summarized in idiom dictionaries; English paraphrases vary.'),
  etymology = COALESCE(etymology, 'Literally scratching an itch through a boot—too indirect to relieve the real discomfort.'),
  historical_context = COALESCE(historical_context, 'Used to criticize superficial fixes in policy, management, and personal advice.'),
  interpretation = COALESCE(interpretation, 'If the intervention never reaches the real constraint, symptoms may persist.'),
  modern_practicality = COALESCE(modern_practicality, 'Prefer targeted fixes and root-cause review over symbolic gestures.'),
  updated_at = now()
WHERE id = '2b4fb088-80e2-4d68-b90b-7daa57f3b043'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['Chinese', 'idiom', 'problem-solving', 'precision']))
) WHERE id = '2b4fb088-80e2-4d68-b90b-7daa57f3b043'::uuid AND deleted_at IS NULL;
INSERT INTO adage_translations (adage_id, language_code, translated_text, translator_notes)
SELECT '2b4fb088-80e2-4d68-b90b-7daa57f3b043'::uuid, 'zh', '隔靴搔癢', 'pinyin: gé xuē sāo yǎng'
WHERE NOT EXISTS (SELECT 1 FROM adage_translations t WHERE t.adage_id = '2b4fb088-80e2-4d68-b90b-7daa57f3b043'::uuid AND t.deleted_at IS NULL AND t.language_code = 'zh');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '2b4fb088-80e2-4d68-b90b-7daa57f3b043'::uuid, 'Taiwan Ministry of Education Idioms Dictionary — 隔靴搔癢. https://dict.idioms.moe.edu.tw/', 'https://dict.idioms.moe.edu.tw/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '2b4fb088-80e2-4d68-b90b-7daa57f3b043'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Taiwan Ministry of Education Idioms Dictionary — 隔靴搔癢. https://dict.idioms.moe.edu.tw/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '2b4fb088-80e2-4d68-b90b-7daa57f3b043'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '2b4fb088-80e2-4d68-b90b-7daa57f3b043'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '2b4fb088-80e2-4d68-b90b-7daa57f3b043'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '2b4fb088-80e2-4d68-b90b-7daa57f3b043'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '2b4fb088-80e2-4d68-b90b-7daa57f3b043'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '2b4fb088-80e2-4d68-b90b-7daa57f3b043'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '2b4fb088-80e2-4d68-b90b-7daa57f3b043'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '2b4fb088-80e2-4d68-b90b-7daa57f3b043'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 70172047-cba8-4610-bc7d-453f0606aad6 — One palm makes no applause
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'One person alone can’t create the needed effect; cooperation/support is required.' ELSE definition END,
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Traditional Chinese idiom; explained in standard reference works.' ELSE origin END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Common in idiom references; English renderings vary.'),
  etymology = COALESCE(etymology, 'One hand cannot clap—audible effect needs contact or partnership.'),
  historical_context = COALESCE(historical_context, 'Used in teamwork, politics, and family settings to stress joint action.'),
  interpretation = COALESCE(interpretation, 'Credit and feasibility often depend on coordination, not solo effort alone.'),
  modern_practicality = COALESCE(modern_practicality, 'Design roles, incentives, and handoffs so shared outcomes are possible.'),
  updated_at = now()
WHERE id = '70172047-cba8-4610-bc7d-453f0606aad6'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['Chinese', 'idiom', 'cooperation', 'success']))
) WHERE id = '70172047-cba8-4610-bc7d-453f0606aad6'::uuid AND deleted_at IS NULL;
INSERT INTO adage_translations (adage_id, language_code, translated_text, translator_notes)
SELECT '70172047-cba8-4610-bc7d-453f0606aad6'::uuid, 'zh', '孤掌難鳴', 'pinyin: gū zhǎng nán míng'
WHERE NOT EXISTS (SELECT 1 FROM adage_translations t WHERE t.adage_id = '70172047-cba8-4610-bc7d-453f0606aad6'::uuid AND t.deleted_at IS NULL AND t.language_code = 'zh');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '70172047-cba8-4610-bc7d-453f0606aad6'::uuid, 'Taiwan Ministry of Education Idioms Dictionary — 孤掌難鳴. https://dict.idioms.moe.edu.tw/', 'https://dict.idioms.moe.edu.tw/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '70172047-cba8-4610-bc7d-453f0606aad6'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Taiwan Ministry of Education Idioms Dictionary — 孤掌難鳴. https://dict.idioms.moe.edu.tw/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '70172047-cba8-4610-bc7d-453f0606aad6'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '70172047-cba8-4610-bc7d-453f0606aad6'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '70172047-cba8-4610-bc7d-453f0606aad6'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '70172047-cba8-4610-bc7d-453f0606aad6'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '70172047-cba8-4610-bc7d-453f0606aad6'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '70172047-cba8-4610-bc7d-453f0606aad6'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '70172047-cba8-4610-bc7d-453f0606aad6'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '70172047-cba8-4610-bc7d-453f0606aad6'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- f2f2111c-8ff1-42bf-922c-bb110038afe0 — No wind, no waves
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'If something is circulating, it may have a cause; similar logic to “no smoke without fire.”' ELSE definition END,
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Traditional Chinese idiom; glossed in standard idiom references.' ELSE origin END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Widely cited in modern commentary; earliest attestations summarized in reference works.'),
  etymology = COALESCE(etymology, 'Waves imply wind—metaphorically, visible effects hint at upstream causes.'),
  historical_context = COALESCE(historical_context, 'Used in rumor, politics, and journalism talk; can also be abused to justify gossip.'),
  interpretation = COALESCE(interpretation, 'Signals deserve investigation, but they are not automatic proof.'),
  modern_practicality = COALESCE(modern_practicality, 'Treat buzz as a prompt to verify, not a verdict.'),
  updated_at = now()
WHERE id = 'f2f2111c-8ff1-42bf-922c-bb110038afe0'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['Chinese', 'idiom', 'evidence', 'speech']))
) WHERE id = 'f2f2111c-8ff1-42bf-922c-bb110038afe0'::uuid AND deleted_at IS NULL;
INSERT INTO adage_translations (adage_id, language_code, translated_text, translator_notes)
SELECT 'f2f2111c-8ff1-42bf-922c-bb110038afe0'::uuid, 'zh', '無風不起浪', 'pinyin: wú fēng bù qǐ làng'
WHERE NOT EXISTS (SELECT 1 FROM adage_translations t WHERE t.adage_id = 'f2f2111c-8ff1-42bf-922c-bb110038afe0'::uuid AND t.deleted_at IS NULL AND t.language_code = 'zh');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT 'f2f2111c-8ff1-42bf-922c-bb110038afe0'::uuid, 'Taiwan Ministry of Education Idioms Dictionary — 無風不起浪. https://dict.idioms.moe.edu.tw/', 'https://dict.idioms.moe.edu.tw/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = 'f2f2111c-8ff1-42bf-922c-bb110038afe0'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Taiwan Ministry of Education Idioms Dictionary — 無風不起浪. https://dict.idioms.moe.edu.tw/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'f2f2111c-8ff1-42bf-922c-bb110038afe0'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'f2f2111c-8ff1-42bf-922c-bb110038afe0'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'f2f2111c-8ff1-42bf-922c-bb110038afe0'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'f2f2111c-8ff1-42bf-922c-bb110038afe0'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'f2f2111c-8ff1-42bf-922c-bb110038afe0'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'f2f2111c-8ff1-42bf-922c-bb110038afe0'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'f2f2111c-8ff1-42bf-922c-bb110038afe0'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'f2f2111c-8ff1-42bf-922c-bb110038afe0'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 0e4ff1fe-281b-4bb8-b572-8a574bbccb90 — When you drink water, think of its source
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'Practice gratitude; remember origins and those who enabled your wellbeing.' ELSE definition END,
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Traditional Chinese idiom; discussed in education encyclopedia entries.' ELSE origin END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Common in moral education contexts; English paraphrases vary.'),
  etymology = COALESCE(etymology, 'Water stands for benefits received; source stands for people and conditions that made them possible.'),
  historical_context = COALESCE(historical_context, 'Used in gratitude rhetoric, mentorship, and civic memorial traditions.'),
  interpretation = COALESCE(interpretation, 'Continuity matters: remembering support can shape fair dealing downstream.'),
  modern_practicality = COALESCE(modern_practicality, 'Acknowledge predecessors, maintain relationships, and cite sources—intellectually and socially.'),
  updated_at = now()
WHERE id = '0e4ff1fe-281b-4bb8-b572-8a574bbccb90'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['Chinese', 'idiom', 'gratitude', 'character']))
) WHERE id = '0e4ff1fe-281b-4bb8-b572-8a574bbccb90'::uuid AND deleted_at IS NULL;
INSERT INTO adage_translations (adage_id, language_code, translated_text, translator_notes)
SELECT '0e4ff1fe-281b-4bb8-b572-8a574bbccb90'::uuid, 'zh', '飲水思源', 'pinyin: yǐn shuǐ sī yuán'
WHERE NOT EXISTS (SELECT 1 FROM adage_translations t WHERE t.adage_id = '0e4ff1fe-281b-4bb8-b572-8a574bbccb90'::uuid AND t.deleted_at IS NULL AND t.language_code = 'zh');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '0e4ff1fe-281b-4bb8-b572-8a574bbccb90'::uuid, 'Taiwan MoE Education Encyclopedia — 飲水思源. https://pedia.cloud.edu.tw/', 'https://pedia.cloud.edu.tw/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '0e4ff1fe-281b-4bb8-b572-8a574bbccb90'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Taiwan MoE Education Encyclopedia — 飲水思源. https://pedia.cloud.edu.tw/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '0e4ff1fe-281b-4bb8-b572-8a574bbccb90'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '0e4ff1fe-281b-4bb8-b572-8a574bbccb90'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '0e4ff1fe-281b-4bb8-b572-8a574bbccb90'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '0e4ff1fe-281b-4bb8-b572-8a574bbccb90'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '0e4ff1fe-281b-4bb8-b572-8a574bbccb90'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '0e4ff1fe-281b-4bb8-b572-8a574bbccb90'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '0e4ff1fe-281b-4bb8-b572-8a574bbccb90'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '0e4ff1fe-281b-4bb8-b572-8a574bbccb90'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 242d7829-7b38-49f4-b0f3-67ce4f18ac41 — Hidden dragons, crouching tigers
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'Hidden talent/power in an apparently ordinary place or person.' ELSE definition END,
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Traditional Chinese idiom; literary and martial-arts contexts are common.' ELSE origin END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Modern use includes film titles and everyday praise; dates vary by medium.'),
  etymology = COALESCE(etymology, 'Dragons and tigers evoke formidable capability concealed in an unremarkable setting.'),
  historical_context = COALESCE(historical_context, 'Used to warn against underestimating rivals, students, or colleagues.'),
  interpretation = COALESCE(interpretation, 'Surface modesty can hide strength; appearances mislead.'),
  modern_practicality = COALESCE(modern_practicality, 'Hire and compete with humility: talent is not always advertised.'),
  updated_at = now()
WHERE id = '242d7829-7b38-49f4-b0f3-67ce4f18ac41'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['Chinese', 'idiom', 'depth', 'perception']))
) WHERE id = '242d7829-7b38-49f4-b0f3-67ce4f18ac41'::uuid AND deleted_at IS NULL;
INSERT INTO adage_translations (adage_id, language_code, translated_text, translator_notes)
SELECT '242d7829-7b38-49f4-b0f3-67ce4f18ac41'::uuid, 'zh', '臥虎藏龍', 'pinyin: wò hǔ cáng lóng'
WHERE NOT EXISTS (SELECT 1 FROM adage_translations t WHERE t.adage_id = '242d7829-7b38-49f4-b0f3-67ce4f18ac41'::uuid AND t.deleted_at IS NULL AND t.language_code = 'zh');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '242d7829-7b38-49f4-b0f3-67ce4f18ac41'::uuid, 'Taiwan Ministry of Education Idioms Dictionary — 臥虎藏龍. https://dict.idioms.moe.edu.tw/', 'https://dict.idioms.moe.edu.tw/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '242d7829-7b38-49f4-b0f3-67ce4f18ac41'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Taiwan Ministry of Education Idioms Dictionary — 臥虎藏龍. https://dict.idioms.moe.edu.tw/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '242d7829-7b38-49f4-b0f3-67ce4f18ac41'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '242d7829-7b38-49f4-b0f3-67ce4f18ac41'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '242d7829-7b38-49f4-b0f3-67ce4f18ac41'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '242d7829-7b38-49f4-b0f3-67ce4f18ac41'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '242d7829-7b38-49f4-b0f3-67ce4f18ac41'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '242d7829-7b38-49f4-b0f3-67ce4f18ac41'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '242d7829-7b38-49f4-b0f3-67ce4f18ac41'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '242d7829-7b38-49f4-b0f3-67ce4f18ac41'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 78ca2594-6e4a-4d6e-900f-ac22d7bad7f2 — A foot is short, an inch is long
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'Everyone/thing has strengths and weaknesses; comparisons should be tempered.' ELSE definition END,
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Traditional Chinese idiom; classical background summarized in idiom references.' ELSE origin END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Common in educational and self-help paraphrase; wording varies.'),
  etymology = COALESCE(etymology, 'Units of measure stand for relative advantage: each tool has limits and uses.'),
  historical_context = COALESCE(historical_context, 'Used to temper ranking contests and invidious comparison.'),
  interpretation = COALESCE(interpretation, 'Competitive superiority depends on the task; humility follows from that fact.'),
  modern_practicality = COALESCE(modern_practicality, 'Match people to roles; avoid single-score rankings for diverse skills.'),
  updated_at = now()
WHERE id = '78ca2594-6e4a-4d6e-900f-ac22d7bad7f2'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['Chinese', 'idiom', 'judgment', 'fairness']))
) WHERE id = '78ca2594-6e4a-4d6e-900f-ac22d7bad7f2'::uuid AND deleted_at IS NULL;
INSERT INTO adage_translations (adage_id, language_code, translated_text, translator_notes)
SELECT '78ca2594-6e4a-4d6e-900f-ac22d7bad7f2'::uuid, 'zh', '尺有所短，寸有所長', ' '
WHERE NOT EXISTS (SELECT 1 FROM adage_translations t WHERE t.adage_id = '78ca2594-6e4a-4d6e-900f-ac22d7bad7f2'::uuid AND t.deleted_at IS NULL AND t.language_code = 'zh');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '78ca2594-6e4a-4d6e-900f-ac22d7bad7f2'::uuid, 'Taiwan Ministry of Education Idioms Dictionary — 尺有所短，寸有所長. https://dict.idioms.moe.edu.tw/', 'https://dict.idioms.moe.edu.tw/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '78ca2594-6e4a-4d6e-900f-ac22d7bad7f2'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Taiwan Ministry of Education Idioms Dictionary — 尺有所短，寸有所長. https://dict.idioms.moe.edu.tw/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '78ca2594-6e4a-4d6e-900f-ac22d7bad7f2'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '78ca2594-6e4a-4d6e-900f-ac22d7bad7f2'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '78ca2594-6e4a-4d6e-900f-ac22d7bad7f2'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '78ca2594-6e4a-4d6e-900f-ac22d7bad7f2'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '78ca2594-6e4a-4d6e-900f-ac22d7bad7f2'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '78ca2594-6e4a-4d6e-900f-ac22d7bad7f2'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '78ca2594-6e4a-4d6e-900f-ac22d7bad7f2'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '78ca2594-6e4a-4d6e-900f-ac22d7bad7f2'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- fa0fc8a2-4943-4d73-9a85-21857a5805ad — Forget the fishing gear as soon as the fish is caught
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'Discard the method or helper once the result is achieved; can imply ingratitude or forgetting the process that made success possible.' ELSE definition END,
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Traditional Chinese chengyu; glossed in standard idiom dictionaries.' ELSE origin END,
  first_known_usage = COALESCE(NULLIF(trim(first_known_usage), ''), 'Classical/literary background summarized in references; English metaphors vary.'),
  etymology = COALESCE(etymology, 'Fish stands for the outcome; gear stands for means and mentors that enabled it.'),
  historical_context = COALESCE(historical_context, 'Used to criticize ingratitude and short memory after success.'),
  interpretation = COALESCE(interpretation, 'Ends matter, but erasing helpers erodes trust for the next cycle.'),
  modern_practicality = COALESCE(modern_practicality, 'Document dependencies, thank contributors, and preserve playbooks—not only trophies.'),
  updated_at = now()
WHERE id = 'fa0fc8a2-4943-4d73-9a85-21857a5805ad'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['Chinese', 'idiom', 'gratitude', 'success']))
) WHERE id = 'fa0fc8a2-4943-4d73-9a85-21857a5805ad'::uuid AND deleted_at IS NULL;
INSERT INTO adage_translations (adage_id, language_code, translated_text, translator_notes)
SELECT 'fa0fc8a2-4943-4d73-9a85-21857a5805ad'::uuid, 'zh', '得魚忘筌', 'pinyin: dé yú wàng quán'
WHERE NOT EXISTS (SELECT 1 FROM adage_translations t WHERE t.adage_id = 'fa0fc8a2-4943-4d73-9a85-21857a5805ad'::uuid AND t.deleted_at IS NULL AND t.language_code = 'zh');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT 'fa0fc8a2-4943-4d73-9a85-21857a5805ad'::uuid, 'Taiwan Ministry of Education Idioms Dictionary — 得魚忘筌. https://dict.idioms.moe.edu.tw/', 'https://dict.idioms.moe.edu.tw/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = 'fa0fc8a2-4943-4d73-9a85-21857a5805ad'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Taiwan Ministry of Education Idioms Dictionary — 得魚忘筌. https://dict.idioms.moe.edu.tw/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'fa0fc8a2-4943-4d73-9a85-21857a5805ad'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'fa0fc8a2-4943-4d73-9a85-21857a5805ad'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), 'fa0fc8a2-4943-4d73-9a85-21857a5805ad'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = 'fa0fc8a2-4943-4d73-9a85-21857a5805ad'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'fa0fc8a2-4943-4d73-9a85-21857a5805ad'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'fa0fc8a2-4943-4d73-9a85-21857a5805ad'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT 'fa0fc8a2-4943-4d73-9a85-21857a5805ad'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = 'fa0fc8a2-4943-4d73-9a85-21857a5805ad'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd — The nail that sticks out gets hammered down
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'Conformity pressure; standing out can be punished or corrected.' ELSE definition END,
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Japanese proverb; avoid claiming a single author.' ELSE origin END,
  updated_at = now()
WHERE id = '1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['Japanese', 'idiom', 'conformity', 'risk']))
) WHERE id = '1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd'::uuid AND deleted_at IS NULL;
INSERT INTO adage_translations (adage_id, language_code, translated_text, translator_notes)
SELECT '1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd'::uuid, 'ja', '出る釘は打たれる', 'romaji: deru kugi wa utareru'
WHERE NOT EXISTS (SELECT 1 FROM adage_translations t WHERE t.adage_id = '1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd'::uuid AND t.deleted_at IS NULL AND t.language_code = 'ja');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd'::uuid, 'Tofugu — explanation of 出る釘は打たれる. https://www.tofugu.com/', 'https://www.tofugu.com/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Tofugu — explanation of 出る釘は打たれる. https://www.tofugu.com/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '1d91e725-d2a8-4cb5-81d3-7b9ad0081dbd'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');


-- 26530783-946e-443c-ac93-6c6036743eb2 — Carpe Diem
UPDATE adages SET
  definition = CASE WHEN length(trim(coalesce(definition, ''))) < 100 THEN 'Focus on the present and act while you can; the future is uncertain.' ELSE definition END,
  origin = CASE WHEN length(trim(coalesce(origin, ''))) < 60 THEN 'Latin phrase popularized by Horace in Odes (Book 1, poem 11); commonly glossed as “seize/pluck the day.”' ELSE origin END,
  updated_at = now()
WHERE id = '26530783-946e-443c-ac93-6c6036743eb2'::uuid AND deleted_at IS NULL;
UPDATE adages SET tags = (
  SELECT ARRAY(SELECT DISTINCT unnest(COALESCE(tags, ARRAY[]::text[]) || ARRAY['Latin', 'idiom', 'time', 'philosophy']))
) WHERE id = '26530783-946e-443c-ac93-6c6036743eb2'::uuid AND deleted_at IS NULL;
INSERT INTO adage_translations (adage_id, language_code, translated_text, translator_notes)
SELECT '26530783-946e-443c-ac93-6c6036743eb2'::uuid, 'la', 'Carpe diem', 'Horace, Odes I.11'
WHERE NOT EXISTS (SELECT 1 FROM adage_translations t WHERE t.adage_id = '26530783-946e-443c-ac93-6c6036743eb2'::uuid AND t.deleted_at IS NULL AND t.language_code = 'la');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '26530783-946e-443c-ac93-6c6036743eb2'::uuid, 'Encyclopaedia Britannica — Carpe diem (Horace/Odes). https://www.britannica.com/', 'https://www.britannica.com/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '26530783-946e-443c-ac93-6c6036743eb2'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Encyclopaedia Britannica — Carpe diem (Horace/Odes). https://www.britannica.com/');
INSERT INTO citations (adage_id, source_text, source_url, source_type, created_at)
SELECT '26530783-946e-443c-ac93-6c6036743eb2'::uuid, 'Merriam-Webster — carpe diem. https://www.merriam-webster.com/', 'https://www.merriam-webster.com/', 'other', now()
WHERE NOT EXISTS (SELECT 1 FROM citations c WHERE c.adage_id = '26530783-946e-443c-ac93-6c6036743eb2'::uuid AND c.deleted_at IS NULL AND c.source_text = 'Merriam-Webster — carpe diem. https://www.merriam-webster.com/');

INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '26530783-946e-443c-ac93-6c6036743eb2'::uuid, '1700-01-01', '1949-12-31', 'common', 'Approximate circulation period used for archive organization; not a claim of exact first appearance.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '26530783-946e-443c-ac93-6c6036743eb2'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1700-01-01');
INSERT INTO adage_timeline (id, adage_id, time_period_start, time_period_end, popularity_level, notes, created_at)
SELECT gen_random_uuid(), '26530783-946e-443c-ac93-6c6036743eb2'::uuid, '1950-01-01', NULL, 'very_common', 'Modern circulation and quotation period; dates approximate and editorial.', now()
WHERE NOT EXISTS (SELECT 1 FROM adage_timeline tl WHERE tl.adage_id = '26530783-946e-443c-ac93-6c6036743eb2'::uuid AND tl.deleted_at IS NULL AND tl.time_period_start = '1950-01-01');

INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '26530783-946e-443c-ac93-6c6036743eb2'::uuid, '0d588e53-a308-420c-9088-2319635562e0'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '26530783-946e-443c-ac93-6c6036743eb2'::uuid AND r.related_adage_id = '0d588e53-a308-420c-9088-2319635562e0'::uuid AND r.relationship_type = 'similar');
INSERT INTO related_adages (adage_id, related_adage_id, relationship_type, notes)
SELECT '26530783-946e-443c-ac93-6c6036743eb2'::uuid, '52154004-5736-4c28-bdd3-90a09626849e'::uuid, 'similar', 'Archive cross-reference'
WHERE NOT EXISTS (SELECT 1 FROM related_adages r WHERE r.adage_id = '26530783-946e-443c-ac93-6c6036743eb2'::uuid AND r.related_adage_id = '52154004-5736-4c28-bdd3-90a09626849e'::uuid AND r.relationship_type = 'similar');

